### ISSUE TITLE
EventActivityScope and RelatedActivityId

### ISSUE THREAD

**Issue by gsteinbacher** [jonwagner/EventSourceProxy#38]
First of all, EventSourceProxy...fantastic library!!

How would you recommend we use the EventActivityScope in Windows Workflow (v3.5).   I want to log information in each method with the same Activity ID but since each method is called by WWF separately I am not sure how to maintain the same Activity ID.

Secondly.  Is there any support for RelatedActivityId in EventSourceProxy?  I have looked everywhere (I think) and can't seem to find any reference to it.

Thanks!

**Comment by jonwagner** [comment]
I tried to make EventActivityScope work with the built-in .NET diagnostic activites. It *should* flow through automatically for you. i.e. if you define a scope, .NET should pick it up and send that ID through WWF and WCF services. I say *should* because I've never tried it.

As for RelatedActivityID, unfortunately, I could never figure out how ETW "transfers" is supposed to work. If you know how you want it to work, give me a few examples and I'll try to fit it in.

**Comment by gsteinbacher** [comment]
The use cases where we want to use the RelatedActivityID we would have to set that value ourselves.  My problem is that I could not any way of setting it.  In the .Net framework v4.5.1 they have provided the ability to set the RelatedActivityId by calling the method WriteEventWithRelatedActivityId instead of just calling WriteEvent.  This ability does not seem to be exposed in the EventSourceProxy (from what I could tell the EventSourceProxy is always calling WriteEvent).

**Comment by jonwagner** [comment]
This should be fixed in net46/netstandard2.0. The tracing library now respects flow of activity ids. There may be more work needed for related activities, but I'm not familiar enough with that. Feel free to re-open.
